package ladok.lpw.service.changeaddress.facadeclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2013-06-20T07:56:16.815+02:00
 * Generated source version: 2.6.2
 * 
 */
@WebServiceClient(name = "ChangeAddressFacadeClientService", 
                  wsdlLocation = "https://lpwtest-su.its.uu.se/cxf/ChangeAddressFetcher?wsdl",
                  targetNamespace = "http://facadeclient.changeaddress.service.lpw.ladok/") 
public class ChangeAddressFacadeClientService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://facadeclient.changeaddress.service.lpw.ladok/", "ChangeAddressFacadeClientService");
    public final static QName ChangeAddressFacadeClientPort = new QName("http://facadeclient.changeaddress.service.lpw.ladok/", "ChangeAddressFacadeClientPort");
    static {
        URL url = null;
        try {
            url = new URL("https://lpwtest-su.its.uu.se/cxf/ChangeAddressFetcher?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ChangeAddressFacadeClientService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://lpwtest-su.its.uu.se/cxf/ChangeAddressFetcher?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ChangeAddressFacadeClientService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ChangeAddressFacadeClientService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ChangeAddressFacadeClientService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ChangeAddressFacadeClientService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ChangeAddressFacadeClientService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ChangeAddressFacadeClientService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ChangeAddressFetcher
     */
    @WebEndpoint(name = "ChangeAddressFacadeClientPort")
    public ChangeAddressFetcher getChangeAddressFacadeClientPort() {
        return super.getPort(ChangeAddressFacadeClientPort, ChangeAddressFetcher.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ChangeAddressFetcher
     */
    @WebEndpoint(name = "ChangeAddressFacadeClientPort")
    public ChangeAddressFetcher getChangeAddressFacadeClientPort(WebServiceFeature... features) {
        return super.getPort(ChangeAddressFacadeClientPort, ChangeAddressFetcher.class, features);
    }

}
