package ladok.lpw.service.registrate.facadeclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2013-06-11T09:03:43.456+02:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://facadeclient.registrate.service.lpw.ladok/", name = "RegistrateFetcher")
@XmlSeeAlso({ObjectFactory.class})
public interface RegistrateFetcher {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getFutureCourseRegSuggestions", targetNamespace = "http://facadeclient.registrate.service.lpw.ladok/", className = "ladok.lpw.service.registrate.facadeclient.GetFutureCourseRegSuggestions")
    @WebMethod
    @ResponseWrapper(localName = "getFutureCourseRegSuggestionsResponse", targetNamespace = "http://facadeclient.registrate.service.lpw.ladok/", className = "ladok.lpw.service.registrate.facadeclient.GetFutureCourseRegSuggestionsResponse")
    public ladok.lpw.service.registrate.facadeclient.CourseSuggestionVO getFutureCourseRegSuggestions(
        @WebParam(name = "arg0", targetNamespace = "")
        ladok.lpw.service.registrate.facadeclient.UserVO arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        boolean arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSemesterRegSuggestions", targetNamespace = "http://facadeclient.registrate.service.lpw.ladok/", className = "ladok.lpw.service.registrate.facadeclient.GetSemesterRegSuggestions")
    @WebMethod
    @ResponseWrapper(localName = "getSemesterRegSuggestionsResponse", targetNamespace = "http://facadeclient.registrate.service.lpw.ladok/", className = "ladok.lpw.service.registrate.facadeclient.GetSemesterRegSuggestionsResponse")
    public ladok.lpw.service.registrate.facadeclient.SemesterSuggestionVO getSemesterRegSuggestions(
        @WebParam(name = "arg0", targetNamespace = "")
        ladok.lpw.service.registrate.facadeclient.UserVO arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        boolean arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        boolean arg3
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "registrate", targetNamespace = "http://facadeclient.registrate.service.lpw.ladok/", className = "ladok.lpw.service.registrate.facadeclient.Registrate")
    @WebMethod
    @ResponseWrapper(localName = "registrateResponse", targetNamespace = "http://facadeclient.registrate.service.lpw.ladok/", className = "ladok.lpw.service.registrate.facadeclient.RegistrateResponse")
    public ladok.lpw.service.registrate.facadeclient.RegistrateVO registrate(
        @WebParam(name = "arg0", targetNamespace = "")
        ladok.lpw.service.registrate.facadeclient.UserVO arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        ladok.lpw.service.registrate.facadeclient.RegistrateVO arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getFutureSemesterRegSuggestions", targetNamespace = "http://facadeclient.registrate.service.lpw.ladok/", className = "ladok.lpw.service.registrate.facadeclient.GetFutureSemesterRegSuggestions")
    @WebMethod
    @ResponseWrapper(localName = "getFutureSemesterRegSuggestionsResponse", targetNamespace = "http://facadeclient.registrate.service.lpw.ladok/", className = "ladok.lpw.service.registrate.facadeclient.GetFutureSemesterRegSuggestionsResponse")
    public ladok.lpw.service.registrate.facadeclient.SemesterSuggestionVO getFutureSemesterRegSuggestions(
        @WebParam(name = "arg0", targetNamespace = "")
        ladok.lpw.service.registrate.facadeclient.UserVO arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        boolean arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        boolean arg3
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCourseRegSuggestions", targetNamespace = "http://facadeclient.registrate.service.lpw.ladok/", className = "ladok.lpw.service.registrate.facadeclient.GetCourseRegSuggestions")
    @WebMethod
    @ResponseWrapper(localName = "getCourseRegSuggestionsResponse", targetNamespace = "http://facadeclient.registrate.service.lpw.ladok/", className = "ladok.lpw.service.registrate.facadeclient.GetCourseRegSuggestionsResponse")
    public ladok.lpw.service.registrate.facadeclient.CourseSuggestionVO getCourseRegSuggestions(
        @WebParam(name = "arg0", targetNamespace = "")
        ladok.lpw.service.registrate.facadeclient.UserVO arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        boolean arg2
    );
}
