package ladok.lpw.service.register.facadeclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2013-06-20T07:56:16.091+02:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://facadeclient.register.service.lpw.ladok/", name = "RegisterFetcher")
@XmlSeeAlso({ObjectFactory.class})
public interface RegisterFetcher {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRegister", targetNamespace = "http://facadeclient.register.service.lpw.ladok/", className = "ladok.lpw.service.register.facadeclient.GetRegister")
    @WebMethod
    @ResponseWrapper(localName = "getRegisterResponse", targetNamespace = "http://facadeclient.register.service.lpw.ladok/", className = "ladok.lpw.service.register.facadeclient.GetRegisterResponse")
    public ladok.lpw.service.register.facadeclient.RegVO getRegister(
        @WebParam(name = "arg0", targetNamespace = "")
        ladok.lpw.service.register.facadeclient.UserVO arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        ladok.lpw.service.register.facadeclient.RegVO arg1
    );
}
